# Generated by Django 5.1.3 on 2024-11-16 09:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raster',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='raster',
            name='rast',
            field=django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='vector',
            name='code',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='vector',
            name='multipoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='vector',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='vector',
            name='pct_leave',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vector',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
