# Generated by Django 5.1.3 on 2024-11-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0002_raster_name_raster_rast_alter_vector_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raster',
            old_name='rast',
            new_name='raster',
        ),
        migrations.AddField(
            model_name='raster',
            name='description',
            field=models.CharField(default='', max_length=128),
        ),
    ]
